package errs

import "net/http"

var (
	StatusContinue                      = NewStatusError("Continue processing", http.StatusContinue)
	StatusSwitchingProtocols            = NewStatusError("Switching protocols", http.StatusSwitchingProtocols)
	StatusProcessing                    = NewStatusError("Processing", http.StatusProcessing)
	StatusOK                            = NewStatusError("Operation successful", http.StatusOK)
	StatusCreated                       = NewStatusError("Resource created", http.StatusCreated)
	StatusAccepted                      = NewStatusError("Request accepted", http.StatusAccepted)
	StatusNonAuthoritativeInformation   = NewStatusError("Non-authoritative information", http.StatusNonAuthoritativeInfo)
	StatusNoContent                     = NewStatusError("No content", http.StatusNoContent)
	StatusResetContent                  = NewStatusError("Reset content", http.StatusResetContent)
	StatusPartialContent                = NewStatusError("Partial content", http.StatusPartialContent)
	StatusMultipleChoices               = NewStatusError("Multiple choices", http.StatusMultipleChoices)
	StatusMovedPermanently              = NewStatusError("Resource moved permanently", http.StatusMovedPermanently)
	StatusFound                         = NewStatusError("Resource found", http.StatusFound)
	StatusSeeOther                      = NewStatusError("See other", http.StatusSeeOther)
	StatusNotModified                   = NewStatusError("Not modified", http.StatusNotModified)
	StatusUseProxy                      = NewStatusError("Use proxy", http.StatusUseProxy)
	StatusTemporaryRedirect             = NewStatusError("Temporary redirect", http.StatusTemporaryRedirect)
	StatusPermanentRedirect             = NewStatusError("Permanent redirect", http.StatusPermanentRedirect)
	StatusBadRequest                    = NewStatusError("Invalid request", http.StatusBadRequest)
	StatusUnauthorized                  = NewStatusError("Unauthorized access", http.StatusUnauthorized)
	StatusPaymentRequired               = NewStatusError("Payment required", http.StatusPaymentRequired)
	StatusForbidden                     = NewStatusError("Access forbidden", http.StatusForbidden)
	StatusNotFound                      = NewStatusError("Resource not found", http.StatusNotFound)
	StatusMethodNotAllowed              = NewStatusError("Method not allowed", http.StatusMethodNotAllowed)
	StatusNotAcceptable                 = NewStatusError("Not acceptable", http.StatusNotAcceptable)
	StatusProxyAuthenticationRequired   = NewStatusError("Proxy authentication required", http.StatusProxyAuthRequired)
	StatusTimeout                       = NewStatusError("Operation timeout", http.StatusRequestTimeout)
	StatusConflict                      = NewStatusError("Conflict", http.StatusConflict)
	StatusGone                          = NewStatusError("Resource gone", http.StatusGone)
	StatusLengthRequired                = NewStatusError("Length required", http.StatusLengthRequired)
	StatusPreconditionFailed            = NewStatusError("Precondition failed", http.StatusPreconditionFailed)
	StatusPayloadTooLarge               = NewStatusError("Payload too large", http.StatusRequestEntityTooLarge)
	StatusURITooLong                    = NewStatusError("URI too long", http.StatusRequestURITooLong)
	StatusUnsupportedMediaType          = NewStatusError("Unsupported media type", http.StatusUnsupportedMediaType)
	StatusRangeNotSatisfiable           = NewStatusError("Range not satisfiable", http.StatusRequestedRangeNotSatisfiable)
	StatusExpectationFailed             = NewStatusError("Expectation failed", http.StatusExpectationFailed)
	StatusImATeapot                     = NewStatusError("I'm a teapot", http.StatusTeapot)
	StatusMisdirectedRequest            = NewStatusError("Misdirected request", http.StatusMisdirectedRequest)
	StatusUnprocessableEntity           = NewStatusError("Unprocessable entity", http.StatusUnprocessableEntity)
	StatusLocked                        = NewStatusError("Locked", http.StatusLocked)
	StatusFailedDependency              = NewStatusError("Failed dependency", http.StatusFailedDependency)
	StatusTooEarly                      = NewStatusError("Too early", http.StatusTooEarly)
	StatusUpgradeRequired               = NewStatusError("Upgrade required", http.StatusUpgradeRequired)
	StatusPreconditionRequired          = NewStatusError("Precondition required", http.StatusPreconditionRequired)
	StatusTooManyRequests               = NewStatusError("Too many requests", http.StatusTooManyRequests)
	StatusRequestHeaderFieldsTooLarge   = NewStatusError("Header fields too large", http.StatusRequestHeaderFieldsTooLarge)
	StatusUnavailableForLegalReasons    = NewStatusError("Unavailable for legal reasons", http.StatusUnavailableForLegalReasons)
	StatusInternalServerError           = NewStatusError("Internal server error", http.StatusInternalServerError)
	StatusNotImplemented                = NewStatusError("Not implemented", http.StatusNotImplemented)
	StatusBadGateway                    = NewStatusError("Bad gateway", http.StatusBadGateway)
	StatusServiceUnavailable            = NewStatusError("Service unavailable", http.StatusServiceUnavailable)
	StatusGatewayTimeout                = NewStatusError("Gateway timeout", http.StatusGatewayTimeout)
	StatusHTTPVersionNotSupported       = NewStatusError("HTTP version not supported", http.StatusHTTPVersionNotSupported)
	StatusVariantAlsoNegotiates         = NewStatusError("Variant also negotiates", http.StatusVariantAlsoNegotiates)
	StatusInsufficientStorage           = NewStatusError("Insufficient storage", http.StatusInsufficientStorage)
	StatusLoopDetected                  = NewStatusError("Loop detected", http.StatusLoopDetected)
	StatusNotExtended                   = NewStatusError("Not extended", http.StatusNotExtended)
	StatusNetworkAuthenticationRequired = NewStatusError("Network authentication required", http.StatusNetworkAuthenticationRequired)
)
